[package]
name = "work_tock2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
derive_more = "0.99.16"
clap = "2.33.3"
clap_conf = "0.1.5"
err_tools = "0.1.1"
anyhow = "1.0.49"
